### PR TITLE
fix ExistentialError

### PR DESCRIPTION
**Pull request by newthis**
fix MessageQueue ExistentialError when run avatar2 code in RemoteMemoryProtocol connect method

### CODE REVIEW

**Comment by mariusmue** [comment]
Hi there,

Thanks for the PR! However, can you elaborate more on the context here? Currently, these queues are expected to be created by the *target* (i.e., Qemu or PandaTarget who implement rmp at the moment).

Hence, I'm wondering what the usecase here is.

**Comment by newthis** [comment]
Hi, sorry, I did not notice this implementation code. My qemu process just crashed when running avatar, so I commented out the qemu target start code in avatar and started qemu in a standalone way.

**Comment by mariusmue** [comment]
Hey, just to be on the safe side: Are you using avatar-qemu? Unfortunately, stock-qemu is not working together with avatar (and does not create the rmp-files, for that matter).

**Comment by newthis** [comment]
Thanks a lot, I got it.

**Pull request closed without merging**
